services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "3001:3001"
    env_file:
      - ./server/.env  
    

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - server
